### ISSUE TITLE
Not deleting messages

### ISSUE THREAD

**Issue by raphattack** [riking/AutoDelete#26]
I set up the bot in a channel with:
```
@AutoDelete set 72h
```

It gives the following warning and does nothing:
```
The number of messages in this channel is over 200. Messages may not be reliably deleted. (Saw: 200)
```

**Comment by FlorianWendelborn** [comment]
I‘m also wondering if there’s any way to fix/workaround this limit. 200 messages is quite little for most discord instances.

In my particular use-case, I have an auto-delete that deletes after 1 month. That means it only works up to 7 messages per day...

Is it possible to implement this? I’d say it should be, given that I can manually delete the older messages without any issues.
