### ISSUE TITLE
Bot not responding on commands

### ISSUE THREAD

**Issue by artemdzyuba** [riking/AutoDelete#29]
Hi! When I first invited the bot, it didn't respond to any commands. Then I kicked it and invited again. It started working. But when I returned after several hours, it agains seems not reacting to any commands

What can be the reason?

**Comment by Maelfyn** [comment]
Try this:
@AutoDelete set 24h 

For some reason the syntax is completely different from all of the documentation I've seen.

**Comment by artemdzyuba** [comment]
Thank you, @Maelfyn . Works like charm
