### ISSUE TITLE
The bot is offline

### ISSUE THREAD

**Issue by aqilald** [riking/AutoDelete#34]
The bot wont delete chats in the server and go offlineee

**Comment by rcriv** [comment]
@riking just making sure you know about this

**Comment by riking** [comment]
We're aware. There have been several attempts to restart it, it keeps
failing eventually.

**Comment by rcriv** [comment]
Oh, thank you! I deleted my post because it had started working again. 

Thanks so much for doing this. My users really noticed its absence! 

Holly

**Comment by roperjonathan** [comment]
Hi have also noticed that the bot is currently offline
