### ISSUE TITLE
Feature request: config flag to ignore pinned messages

### ISSUE THREAD

**Issue by izcet** [riking/AutoDelete#40]
It would be useful to use the pinned messages feature to mark important messages that shouldn't be automatically deleted, while still deleting the rest after the configured time.

**Comment by JoghurtConnaisseur** [comment]
Yes, I also need this feature and no bot (I found) can do that. I'm trying to create a channel, where the bot commands list is always kept in the channel and actual commands by users get deleted.

**Comment by riking** [comment]
Already ignores pinned messages, but there's a bug where it sometimes deletes them anyways.
