### ISSUE TITLE
Stopped Deleting and Responding

### ISSUE THREAD

**Issue by RedSeal** [riking/AutoDelete#50]
Seems the bot has stopped deleting in a channel that has been setup for a very long time. I tried to reset the settings but `@AutoDelete set 0` and then setting it back to our original setting, but it seems the bot won't respond to any commands. Not even `@AutoDelete help`.

**Comment by corgipicks** [comment]
This is also the case for me. Have tried several things with 0 response from bot.

**Comment by w1kk1** [comment]
bot is down, check discord for more info

**Comment by zsophiie** [comment]
same problem since 7 days

**Comment by snab43** [comment]
> bot is down, check discord for more info

Having relevant debug information exclusively in a Discord server is one of the most annoying development trends as of late. It's bad practice to confine that kind of information on the deep web.

So for anyone else coming here looking for answers, here you go, copy and pasted from the #announce channel:

(From the developer)
> Job has been draining me and I haven't been able to check on the bot operation. I'm aware of the complaints but haven't been able to do anything about them.
> My motivation to fix operational problems went to zero when it started hitting Discord global rate limits, and Discord support never answered requests to increase the limits to keep up with demand.

Sounds like the bot is likely dead.

Thanks for maintaining this for so long and making it open source, it was a good bot I appreciated using.

**Comment by ChaosEmpire** [comment]
oh no!!!
there is no replacement

**Comment by RedSeal** [comment]
> oh no!!! there is no replacement

I was able to get what I need from https://interpunct.info/

-- Also gonna close this issue
